---
title: "Untitled"
author: "Azzahra Galih"
date: "12/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(e1071) #untuk naive bayes
library(caret) #untuk klasifikasi data
library(syuzhet) #untuk membaca fungsi get_nrc
library(tm)
library(dplyr)
library(RTextTools)

datareview <- read.csv("clean_earphone.csv",stringsAsFactors = FALSE)
review <- as.character(datareview$text) #merubah text menjadi char
s <- get_nrc_sentiment(review)

review_combine <- cbind(datareview$text,s) #klasifikasi data

#Pembentukan hasil sentimen analisis NRC 
sentiment <- data.frame(negative=s$negative, positive=s$positive)
classify <- mutate(sentiment, text_sentiment= ifelse((sentiment$negative != sentiment$positive),
                                              ifelse(sentiment$negative !=0, print("Negative"),
                                                      print("Positive")),
                                                      print("Neutral")
                                                     ))
df<-data.frame(text=review,sentimen=classify$text_sentiment)

par(mar=rep(3,4))
a <- barplot(colSums(s),col=rainbow(10),ylab='count',main='Scatter Plot Sentiment Analisi Earphone')
brplt <- a
```



```{r}
library(tm)
    
data_earphone=as.factor(datareview$text)
corpus= Corpus(VectorSource(data_earphone))
fw <- TermDocumentMatrix(corpus)
fw <- removeSparseTerms(fw, sparse=0.98)
fw <- as.matrix(fw)

w = sort(rowSums(fw),decreasing = TRUE)
barplot(w[1:8],
        las=2,
        main="Frequency of Words",
        col= rainbow(15))
```



```{r}
    
#library untuk penggunaan corpus dalam cleaning data
library(tm)
library(RTextTools)
#library yang terdapat sebuah algoritma naivebayes
library(e1071)
library(dplyr)
library(caret)
df<-read.csv("clean_earphone.csv",stringsAsFactors = FALSE)
glimpse(df)

set.seed(20)
df<-df[sample(nrow(df)),]
df<-df[sample(nrow(df)),]
glimpse(df)

corpus<-Corpus(VectorSource(df$text))
corpus
inspect(corpus[1:10])
#fungsinya untuk membersihkan data data yang tidak dibutuhkan 
corpus.clean<-corpus%>%
    tm_map(content_transformer(tolower))%>%
    tm_map(removePunctuation)%>%
    tm_map(removeNumbers)%>%
    tm_map(removeWords,stopwords(kind="en"))%>%
    tm_map(stripWhitespace)
dtm<-DocumentTermMatrix(corpus.clean)

inspect(dtm[1:10,1:20])

df.train<-df[1:50,]
df.test<-df[51:100,]

dtm.train<-dtm[1:50,]
dtm.test<-dtm[51:100,]

corpus.clean.train<-corpus.clean[1:50]
corpus.clean.test<-corpus.clean[51:100]

dim(dtm.train)
fivefreq<-findFreqTerms(dtm.train,5)
length(fivefreq)

dtm.train.nb<-DocumentTermMatrix(corpus.clean.train,control = list(dictionary=fivefreq))

dtm.test.nb<-DocumentTermMatrix(corpus.clean.test,control = list(dictionary=fivefreq))

dim(dtm.test.nb)
 
convert_count <- function(x){
    y<-ifelse(x>0,1,0)
    y<-factor(y,levels=c(0,1),labels=c("no","yes"))
    y
}
trainNB<-apply(dtm.train.nb,2,convert_count)
testNB<-apply(dtm.test.nb,1,convert_count)


library(wordcloud)
world_cloud<-wordcloud(corpus.clean,min.freq = 4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
```


```{r}
library(markdown)
library(DT)
library(shiny)
library(wordcloud)
ui <- fluidPage(
  
    titlePanel("Review Earphone di Amazon"),
    mainPanel(
      tabsetPanel(type = "tabs",
              tabPanel("Data Review",DT::dataTableOutput('data')),
              tabPanel("Scatterplot",plotOutput('scatterplot')),
              tabPanel("Frequency Words", plotOutput('freq')),
              tabPanel("Worldcloud", plotOutput('wc'))
        )
    )
)

   #r server
library(shiny)
server <- function(input, output){
  
  output$data <- DT:: renderDataTable({
    DT::datatable(df, options = list(lenghtChange = FALSE))
  })
  
   output$scatterplot <- renderPlot({
    barplot(colSums(s),
           col=rainbow(10),
           ylab ='count',
           main='Scatter Plot Sentiment Analisi Earphone')
  })
   
    output$freq <- renderPlot({
    barplot(w[1:5],
        las=2,
        main="Frequency of Words",
        col= rainbow(15))
  })
    
     output$wc <- renderPlot({
       world_cloud<-wordcloud(corpus.clean,min.freq = 4,max.words=100,random.order=F,colors=brewer.pal(8,"Dark2"))
     })
}
shinyApp(ui=ui,server=server,options=list(height="1080px"))
```
